const Sector = require('../models/Sector');
const Alert = require('../models/Alert');

const initialSectors = [
  {
    sectorId: 'S01',
    name: 'Triveni Sangam',
    zone: 'SANGAM',
    capacity: 85000,
    currentOccupancy: 72000,
    density: 84.7,
    status: 'RED',
    coordinates: { x: 5, y: 4, lat: 25.4358, lng: 81.8463 },
    adjacentSectors: ['S02', 'S03', 'S07'],
    inflow: 3200,
    outflow: 1800,
    resourcesDeployed: { police: 45, medics: 12, volunteers: 80 },
  },
  {
    sectorId: 'S02',
    name: 'Sector-1 Ghat',
    zone: 'GHAT',
    capacity: 60000,
    currentOccupancy: 38000,
    density: 63.3,
    status: 'YELLOW',
    coordinates: { x: 3, y: 4, lat: 25.437, lng: 81.842 },
    adjacentSectors: ['S01', 'S04', 'S05'],
    inflow: 1800,
    outflow: 2100,
    resourcesDeployed: { police: 28, medics: 8, volunteers: 45 },
  },
  {
    sectorId: 'S03',
    name: 'Allahabad Railway Station',
    zone: 'TRANSIT',
    capacity: 50000,
    currentOccupancy: 21000,
    density: 42.0,
    status: 'GREEN',
    coordinates: { x: 6, y: 2, lat: 25.4478, lng: 81.8394 },
    adjacentSectors: ['S01', 'S06', 'S08'],
    inflow: 4500,
    outflow: 4200,
    resourcesDeployed: { police: 35, medics: 10, volunteers: 60 },
  },
  {
    sectorId: 'S04',
    name: 'Hanuman Mandir Zone',
    zone: 'TEMPLE',
    capacity: 40000,
    currentOccupancy: 37500,
    density: 93.75,
    status: 'CRITICAL',
    coordinates: { x: 2, y: 5, lat: 25.4349, lng: 81.844 },
    adjacentSectors: ['S02', 'S05'],
    inflow: 2800,
    outflow: 900,
    resourcesDeployed: { police: 55, medics: 18, volunteers: 100 },
  },
  {
    sectorId: 'S05',
    name: 'Sector-4 Parking Hub',
    zone: 'TRANSIT',
    capacity: 75000,
    currentOccupancy: 28000,
    density: 37.3,
    status: 'GREEN',
    coordinates: { x: 2, y: 3, lat: 25.441, lng: 81.836 },
    adjacentSectors: ['S02', 'S04', 'S09'],
    inflow: 6000,
    outflow: 5800,
    resourcesDeployed: { police: 20, medics: 5, volunteers: 30 },
  },
  {
    sectorId: 'S06',
    name: 'Naini Bridge Crossing',
    zone: 'TRANSIT',
    capacity: 30000,
    currentOccupancy: 26500,
    density: 88.3,
    status: 'RED',
    coordinates: { x: 8, y: 3, lat: 25.4389, lng: 81.8587 },
    adjacentSectors: ['S03', 'S07', 'S10'],
    inflow: 2100,
    outflow: 800,
    resourcesDeployed: { police: 40, medics: 14, volunteers: 70 },
  },
  {
    sectorId: 'S07',
    name: 'Sangam Mela Camp A',
    zone: 'CAMP',
    capacity: 120000,
    currentOccupancy: 68000,
    density: 56.7,
    status: 'YELLOW',
    coordinates: { x: 6, y: 5, lat: 25.432, lng: 81.851 },
    adjacentSectors: ['S01', 'S06', 'S08'],
    inflow: 3500,
    outflow: 3200,
    resourcesDeployed: { police: 30, medics: 9, volunteers: 55 },
  },
  {
    sectorId: 'S08',
    name: 'VIP & Media Zone',
    zone: 'COMMERCIAL',
    capacity: 15000,
    currentOccupancy: 4200,
    density: 28.0,
    status: 'GREEN',
    coordinates: { x: 7, y: 2, lat: 25.4502, lng: 81.848 },
    adjacentSectors: ['S03', 'S07'],
    inflow: 400,
    outflow: 380,
    resourcesDeployed: { police: 15, medics: 4, volunteers: 10 },
  },
  {
    sectorId: 'S09',
    name: 'Sector-6 Bus Terminal',
    zone: 'TRANSIT',
    capacity: 55000,
    currentOccupancy: 18000,
    density: 32.7,
    status: 'GREEN',
    coordinates: { x: 1, y: 2, lat: 25.445, lng: 81.828 },
    adjacentSectors: ['S05', 'S10'],
    inflow: 7000,
    outflow: 6800,
    resourcesDeployed: { police: 18, medics: 4, volunteers: 25 },
  },
  {
    sectorId: 'S10',
    name: 'Jhunsi Ghat Sector',
    zone: 'GHAT',
    capacity: 45000,
    currentOccupancy: 31000,
    density: 68.9,
    status: 'YELLOW',
    coordinates: { x: 9, y: 4, lat: 25.428, lng: 81.866 },
    adjacentSectors: ['S06', 'S09'],
    inflow: 1500,
    outflow: 1600,
    resourcesDeployed: { police: 22, medics: 6, volunteers: 35 },
  },
  {
    sectorId: 'S11',
    name: 'Akshayavat Temple',
    zone: 'TEMPLE',
    capacity: 25000,
    currentOccupancy: 19800,
    density: 79.2,
    status: 'YELLOW',
    coordinates: { x: 4, y: 6, lat: 25.433, lng: 81.843 },
    adjacentSectors: ['S01', 'S04'],
    inflow: 1200,
    outflow: 1050,
    resourcesDeployed: { police: 25, medics: 7, volunteers: 40 },
  },
  {
    sectorId: 'S12',
    name: 'Mela Camp B - North',
    zone: 'CAMP',
    capacity: 100000,
    currentOccupancy: 42000,
    density: 42.0,
    status: 'GREEN',
    coordinates: { x: 4, y: 1, lat: 25.457, lng: 81.84 },
    adjacentSectors: ['S03', 'S05', 'S09'],
    inflow: 2800,
    outflow: 2700,
    resourcesDeployed: { police: 16, medics: 5, volunteers: 28 },
  },
];

const initialAlerts = [
  {
    alertId: 'ALT001',
    type: 'STAMPEDE_RISK',
    severity: 'CRITICAL',
    sectorId: 'S04',
    sectorName: 'Hanuman Mandir Zone',
    message: 'Occupancy at 93.75%. Immediate crowd dispersal required. Risk of crush injury.',
    isActive: true,
    metadata: { occupancy: 93.75, threshold: 85 },
  },
  {
    alertId: 'ALT002',
    type: 'BOTTLENECK',
    severity: 'HIGH',
    sectorId: 'S06',
    sectorName: 'Naini Bridge Crossing',
    message: 'Critical bottleneck at bridge entry. Inflow exceeds outflow by 1300 pilgrims/min.',
    isActive: true,
    metadata: { inflow: 2100, outflow: 800 },
  },
  {
    alertId: 'ALT003',
    type: 'OVERCROWDING',
    severity: 'HIGH',
    sectorId: 'S01',
    sectorName: 'Triveni Sangam',
    message: 'Triveni Sangam at 84.7% capacity. Deploy additional flow control personnel.',
    isActive: true,
    metadata: { density: 84.7 },
  },
];

async function seedDatabase() {
  try {
    const sectorCount = await Sector.countDocuments();
    if (sectorCount === 0) {
      await Sector.insertMany(initialSectors);
      console.log('Sectors seeded successfully');
    }

    const alertCount = await Alert.countDocuments();
    if (alertCount === 0) {
      await Alert.insertMany(initialAlerts);
      console.log('Alerts seeded successfully');
    }
  } catch (err) {
    console.error('Seeding error:', err.message);
  }
}

module.exports = { seedDatabase, initialSectors };